name: Build and deploy React app to Azure Web App - ace-academy-web

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: LIVESPEECH/livespeech-react

      - name: Build React app
        run: npm run build
        working-directory: LIVESPEECH/livespeech-react

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ace-academy-web'
          package: LIVESPEECH/livespeech-react/build
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_ACE_ACADEMY_WEB }}
